# Generated by Django 5.1 on 2024-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('nights', models.IntegerField(default=1)),
                ('bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
    ]
